version: "3"
services:
    frontend:
        build: ./ClientApp/.
        image: featurerequestclientapp:latest
        networks:
            - overlay
        depends_on:
            - backend
    backend:
        build: ./FeatureRequestAPI/FeatureRequestAPI/.
        image: featurerequestapi:latest
        networks:
            - overlay

networks:
  overlay:


